comment unused function write_mucounteren
Fix issue when build share library

/usr/bin/ld: libqemu-riscv64-softmmu.fa.p/target_riscv_csr.c.o: in function `write_mucounteren':
/work/vp.buildv2/libs/qbox.build/../../../libs/qbox/target/riscv/csr.c:4375: undefined reference to `icount_shift_flag'

Signed-off-by: Huaqi Fang <578567190@qq.com>